/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/exception/403.vue')['default']
    404: typeof import('./src/components/exception/404.vue')['default']
    500: typeof import('./src/components/exception/500.vue')['default']
    Breadcrumb: typeof import('./src/components/layout/Breadcrumb.vue')['default']
    Buttons: typeof import('./src/components/exception/buttons.vue')['default']
    Demo: typeof import('./src/components/search/demo/index.vue')['default']
    Error403: typeof import('./src/components/exception/error-403.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Logo: typeof import('./src/components/layout/Logo.vue')['default']
    Nav: typeof import('./src/components/layout/Nav.vue')['default']
    Router: typeof import('./src/components/layout/Router.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/layout/Setting.vue')['default']
    Siderbar: typeof import('./src/components/layout/Siderbar.vue')['default']
  }
}
